name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: 213899591783.dkr.ecr.ap-northeast-3.amazonaws.com
        ECR_REPOSITORY: gitops-repo
        NEW_TAG: ${{ github.run_number }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$NEW_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$NEW_TAG

    - name: Update Deployment YAML
      env:
        NEW_TAG: ${{ github.run_number }}
      run: |
        sed -i "s|image: .*|image: 213899591783.dkr.ecr.ap-northeast-3.amazonaws.com/gitops-repo:${NEW_TAG}|" k8s/deployment.yaml

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
        git add k8s/deployment.yaml
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update image to ${NEW_TAG}"; git push)
